### ISSUE TITLE
Design of the “handle URLs” 

### ISSUE THREAD

**Issue by Ham-png** [461-Team-14/Project-1#14]

**Comment by Ham-png** [comment]
I finished writing my handling URL part @paretosha30 @huntingh @sdlott

Take a look whenever you guys can!

**Comment by sdlott** [comment]
@Ham-png Where?

**Comment by Ham-png** [comment]
Shouldn't it be in the document?

**Comment by sdlott** [comment]
Found it ty!

**Comment by sdlott** [comment]
@Ham-png We need to return more than just the URL and the score. Look at the 6 attributes on the spec doc. Also, I'd provide more details on how you are going to differentiate an npm and GitHub.

**Comment by Ham-png** [comment]
There isn't supposed to be much differentiation between GitHub and npm for score determination because I actually asked the Professor, and he asked how our algorithm will support other sites, so everything is supposed to be built by sharing functionality.

**Comment by Ham-png** [comment]
I added more to my section if you guys want to check it out.
